version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install -g pnpm
            - pnpm install
        build:
          commands:
            - pnpm build:only
      artifacts:
        baseDirectory: ".next"
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: conversational-ui