version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: issue-solver-localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack_data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-west-3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - TMPDIR=/tmp/localstack_tmp
    ports:
      - "4566:4566"  # LocalStack main endpoint
    volumes:
      - "${TMPDIR:-/tmp}/localstack_data:/tmp/localstack_data"
      - "${TMPDIR:-/tmp}/localstack_tmp:/tmp/localstack_tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"

  localstack-init:
    image: amazon/aws-cli:latest
    container_name: issue-solver-localstack-init
    depends_on:
      - localstack
    environment:
      - AWS_DEFAULT_REGION=eu-west-3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for LocalStack to be ready...' &&
      sleep 10 &&
      echo 'Creating SQS queue...' &&
      aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name process-queue &&
      echo 'SQS queue created successfully!'
      "
    restart: "no"
  postgres:
    image: postgres:17-alpine
    container_name: postgres-umansbackenddb
    environment:
      POSTGRES_USER: cudu
      POSTGRES_PASSWORD: s3cr3tPAssw0rd
      POSTGRES_DB: umansbackenddb
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-umans-backend
    ports:
      - "63799:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  localstack_data:
  redis_data: