# gitlab-ci/solve-issues.yml
include:
  - remote: 'https://raw.githubusercontent.com/umans-tech/issue-solver-bots/main/gitlab-ci/solve-issues-template.yml'

solve-issues:
  stage: code
  variables:
    AGENT: SWE-agent  # Default value for AGENT
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
  extends:
    - .solve-issues
