
.solve-issues:
  image: python:3.10-alpine
  services:
    - name: docker:dind
  before_script:
    - apk update && apk add docker git jq curl
    - echo "📥 Downloading the solve_issues.sh script"
    - curl -o solve_issues.sh https://raw.githubusercontent.com/umans-tech/issue-solver-bots/main/scripts/solve_issues.sh
    - chmod +x solve_issues.sh

  script:
    - sh solve_issues.sh
  after_script:
    - echo "🧹 Cleaning up"
    - rm -f solve_issues.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web" && ($GITLAB_ISSUE_ID || $ISSUE_URL || $ISSUE_DESCRIPTION)'
    - when: manual

