name: Continuous Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'operations/01-provision/**'
      - 'operations/02-deploy/**'
      - 'conversational-ui/**'
      - 'issue-solver/**'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    paths:
      - 'operations/01-provision/**'
      - 'operations/02-deploy/**'
      - 'conversational-ui/**'
      - 'issue-solver/**'

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      provision-changes: ${{ steps.filter.outputs.provision }}
      deploy-changes: ${{ steps.filter.outputs.deploy }}
      app-changes: ${{ steps.filter.outputs.app }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            provision:
              - 'operations/01-provision/**'
            deploy:
              - 'operations/02-deploy/**'
            app:
              - 'conversational-ui/**'
              - 'issue-solver/**'

  provision:
    needs: detect-changes
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.detect-changes.outputs.provision-changes == 'true') ||
      (github.event_name == 'pull_request' && github.event.action != 'closed' && (needs.detect-changes.outputs.provision-changes == 'true' || needs.detect-changes.outputs.deploy-changes == 'true' || needs.detect-changes.outputs.app-changes == 'true'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      # Add authentication steps here if needed
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034362042699:role/GitHubActionsRole
          role-session-name: SessionGitHubActions
          aws-region: eu-west-3

      - name: Apply provision
        run: |
          cd operations/01-provision
          terraform init -reconfigure
          just apply
        env:
          GH_PR_NUMBER: ${{ github.event.pull_request.number }}
          TF_VAR_supabase_token: ${{ secrets.TF_VAR_SUPABASE_TOKEN }}
          TF_VAR_supabase_organization_slug: ${{ secrets.TF_VAR_SUPABASE_ORGANIZATION_SLUG }}

  deploy:
    needs: [ detect-changes, provision ]
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main' && (needs.detect-changes.outputs.deploy-changes == 'true' || needs.detect-changes.outputs.app-changes == 'true')) ||
      (github.event_name == 'pull_request' && github.event.action != 'closed' && (needs.detect-changes.outputs.deploy-changes == 'true' || needs.detect-changes.outputs.app-changes == 'true'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      # Add authentication steps here if needed
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034362042699:role/GitHubActionsRole
          role-session-name: SessionGitHubActions
          aws-region: eu-west-3

      - name: Apply deploy
        run: |
          cd operations/02-deploy
          terraform init -reconfigure
          just apply
        env:
          GH_PR_NUMBER: ${{ github.event.pull_request.number }}
          TF_VAR_auth_secret: ${{ secrets.TF_VAR_AUTH_SECRET }}
          TF_VAR_openai_api_key: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          TF_VAR_anthropic_api_key: ${{ secrets.TF_VAR_ANTHROPIC_API_KEY }}
          TF_VAR_google_generative_ai_api_key: ${{ secrets.TF_VAR_GOOGLE_GENERATIVE_AI_API_KEY }}
          TF_VAR_vercel_api_token: ${{ secrets.TF_VAR_VERCEL_API_TOKEN }}

  cleanup:
    needs: detect-changes
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      
      # Add authentication steps here if needed
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034362042699:role/GitHubActionsRole
          role-session-name: SessionGitHubActions
          aws-region: eu-west-3

      - name: Destroy deploy
        run: |
          cd operations/02-deploy
          terraform init -reconfigure
          just destroy
        env:
          GH_PR_NUMBER: ${{ github.event.pull_request.number }}
          TF_VAR_auth_secret: ${{ secrets.TF_VAR_AUTH_SECRET }}
          TF_VAR_openai_api_key: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
          TF_VAR_anthropic_api_key: ${{ secrets.TF_VAR_ANTHROPIC_API_KEY }}
          TF_VAR_google_generative_ai_api_key: ${{ secrets.TF_VAR_GOOGLE_GENERATIVE_AI_API_KEY }}
          TF_VAR_vercel_api_token: ${{ secrets.TF_VAR_VERCEL_API_TOKEN }}

      - name: Destroy provision
        run: |
          cd operations/01-provision
          terraform init -reconfigure
          just destroy
        env:
          GH_PR_NUMBER: ${{ github.event.pull_request.number }}
          TF_VAR_supabase_token: ${{ secrets.TF_VAR_SUPABASE_TOKEN }}
          TF_VAR_supabase_organization_slug: ${{ secrets.TF_VAR_SUPABASE_ORGANIZATION_SLUG }} 