name: Continuous Integration for "issue-solver" Python project

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'    # e.g. v1.0.0, v2.3.4
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./issue-solver

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint the project
        run: just lint

      - name : Check the typing
        run: just check-typing

      - name: Run tests
        run: just test
  publish:
    name: Build and Publish to PyPI
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # only run if it's a tag matching 'v*'
    defaults:
      run:
        working-directory: ./issue-solver

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build distribution
        run: uv build

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}